### ISSUE TITLE
Watson API利用方法を展開する

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [tomoyuki-nakabayashi/ICS-IoT-hackathon#17]

**Comment by tomoyuki-nakabayashi** [comment]
Visual Recognitionのサービスはインスタンス化してあるので、使えます。

NodeRED：
http://qiita.com/y-some/items/f1e74aafb194ac9b72ff

python：
http://qiita.com/himenoglyph/items/f11cbbaf15794a426c5d

**Comment by wonderler** [comment]
多分ここがAPI仕様
https://www.ibm.com/watson/developercloud/visual-recognition/api/v3/#introduction
基本はREST APIのようなので、言語は何でもいい
リクエストの送受信ができればOK
英語だけど、そこまで難しくないと思う

**Comment by tomoyuki-nakabayashi** [comment]
使えるようになったのでclose.
