### ISSUE TITLE
dalchymia APIの調査が必要

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [tomoyuki-nakabayashi/ICS-IoT-hackathon#3]
MQTTは中林が把握済。

**Comment by wonderler** [comment]
RESTベースのWeb APIで、javaのサンプルからおおまかなAPIが分かる。
ベースURI：https://api.dalchymia.net/api/v3/
ログインは以外のURIでBASIC認証
https://api.dalchymia.net/api/v3/auth/login

データ取得は、デバイスIDを指定する必要がある
https://api.dalchymia.net/api/v3/data/[deviceID]
ソースではパースしてるので、何らかの変換は必要かも。

**Comment by tomoyuki-nakabayashi** [comment]
MQTTは中林、Web APIはわだけんに聞く。
