### ISSUE TITLE
フロントエンドを何で作るか未決定

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [tomoyuki-nakabayashi/ICS-IoT-hackathon#4]
当面は、google chartでグラフ化できれば十分？

**Comment by wonderler** [comment]
実行環境を考慮すると、html+javascriptが良いのでは。
ブラウザとネットワークがあれば、実行（デバッグ）は容易で、サーバ不要。
これが一番大きなメリット。
データのモックを作れば、誰でも、何処でも開発できる。
デメリットは、ブラウザやクライアントスペック依存が多少あるが、大きな問題とは思えない。

技術的な部分は、サンプル及びネット調査で大丈夫でしょう。

**Comment by wonderler** [comment]
【追記】
google chartについては、ドキュメント（英語）を参照すれば特殊な場合を除いて問題無いと思われる。
リアルタイム性も問題ないと思うが、これについては更新頻度とデータ取得にかかる時間に依存する。
問題は、サンプルがないこと。
付属サンプルのhtmlは、ある期間のデータをまとめて取ってきて、チャートに描画している。
このあたり、必要性を検討して、どのような方針にするかを決める必要がある。

**Comment by tomoyuki-nakabayashi** [comment]
サンキュー！
とりあえず使えそうなので、使ってみて、何が足りないか考えよう。
